import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync } from "fs";
import { join } from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
if(typeof process==="undefined"){var process={nextTick:function(fn){return Promise.resolve().then(fn)},env:{},browser:true};}
if(typeof setImmediate==="undefined"){var setImmediate=function(fn){return Promise.resolve().then(fn);};}
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2016",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

// ── Copiar el worker de pdf.js junto a main.js ──────────────────────────────
// El worker DEBE existir en el directorio del plugin instalado.
// En dev (watch) se copia aquí (raíz del proyecto).
// En producción se incluye en el release junto a main.js y manifest.json.
try {
	const workerSrc = join(
		"node_modules",
		"pdfjs-dist",
		"legacy",
		"build",
		"pdf.worker.min.js",
	);
	copyFileSync(workerSrc, "pdf.worker.min.js");
	console.log("[esbuild] pdf.worker.min.js copiado al directorio raíz ✓");
} catch (e) {
	console.warn("[esbuild] No se pudo copiar pdf.worker.min.js:", e.message);
}

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
